# Generated by Django 5.1.7 on 2025-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_alter_clothupload_upload_type_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothupload',
            name='upload_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('recycle', 'Recycle'), ('thrift', 'Thrift'), ('renting', 'Renting')], max_length=20),
        ),
    ]
