# Generated by Django 5.2 on 2025-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rentalrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='dropoff', max_length=50, null=True),
        ),
    ]
